QC/urls.py
"""
Definition of urls for QC.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.urls import include, path
from . import PptNew01

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('emplist/', include('emplist.urls')),
    path('pptxlist/', include('pptxlist.urls')),
    path('QC', PptNew01.index, name='index'),
    path('vid02/', include('vid02.urls'))
]

emplist/urls.py
from django.urls import path, include

from . import views

app_name = 'emplist'

urlpatterns = [
	path('', views.index, name='index'),
	path('<int:employee_id>/detail', views.detail, name='detail'),
	path('<int:employee_id>/genpptx', views.genpptx, name='genpptx'),
	path('registform', views.registform, name='registform'),
	path('regist', views.regist, name='regist'),
]

genpdf/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('emplist/', include('emplist.urls')),
    path('pptxlist/', include('pptxlist.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emplist/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
	firstname_text = models.CharField(max_length=200)
	lastname_text = models.CharField(max_length=200)

	address_text = models.CharField(max_length=200)

	phone_text = models.CharField(max_length=200)

	def __str__(self):
		return self.firstname_text + ' ' + self.lastname_text
	

emplist/views.py
from django.shortcuts import render

from pptx import Presentation
from pptx.util import Inches

from .models import Employee

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Employee

from thumbnail import generate_thumbnail

def index(request):
	employee_list = Employee.objects.all()
	return render(request, 'emplist/list.html', {'employee_list': employee_list })

def detail(request, employee_id):

	emp = get_object_or_404(Employee, pk=employee_id)
	return render(request, 'emplist/detail.html', {'employee': emp })

def genpptx(reqeust, employee_id):

	emp = Employee.objects.get( pk=employee_id )

	prs = Presentation()
	title_slide_layout = prs.slide_layouts[0]
	slide = prs.slides.add_slide(title_slide_layout)
	shapes = slide.shapes

	shapes.title.text = 'Sample Table'

	rows = 4
	cols = 2
	left = top = Inches(2.0)
	width = Inches(6.0)
	height = Inches(0.8)

	table = shapes.add_table(rows, cols, left, top, width, height).table

	table.columns[0].width = Inches(2.0)
	table.columns[1].width = Inches(4.0)

	table.cell(0,0).text = 'First Name'
	table.cell(0,1).text = emp.firstname_text

	table.cell(1,0).text = 'Last Name'
	table.cell(1,1).text = emp.lastname_text

	table.cell(2,0).text = 'Address'
	table.cell(2,1).text = emp.address_text

	table.cell(3,0).text = 'Phone'
	table.cell(3,1).text = emp.phone_text

	prs.save('test.pptx')

	######################
	# Generate a thumbnail
	######################

	options = {
		'trim': False,
		'height': 300,
		'width': 300,
		'quality': 85,
		'type': 'thumbnail'
	}

	generate_thumbnail('test.pptx', 'thumbnail.png', options )

	file = open("test.pptx", "rb")

	response = HttpResponse(file.read(), content_type="application/pptx")
	response['Content-Disposition'] = 'attachment; filename=%s' % emp.firstname_text + '.pptx'
	return response

def regist(request):

	firstname = request.POST['firstname']
	lastname = request.POST['lastname']
	address = request.POST['address']
	phone = request.POST['phone']

	emp = Employee( firstname_text=firstname, lastname_text=lastname, address_text=address, phone_text = phone )
	emp.save()

	employee_list = Employee.objects.all()
	return render(request, 'emplist/list.html', {'employee_list': employee_list })



		
def registform(request):

	return render(request, 'emplist/registform.html')

emplist/templates/emplist/detail.html
	<form action="{% url 'emplist:genpptx' employee.id %}" method="post">
	{% csrf_token %}
		<p>First Name</p>
		<ul>
			{{ employee.firstname_text }}
		</ul>
		<p>Last Name</p>
		<ul>
			{{ employee.lastname_text }}
		</ul>
		<p>Address</p>
		<ul>
			{{ employee.address_text }}
		</ul>
		<p>Phone</p>
		<ul>
			{{ employee.phone_text }}
		</ul>

		<input type="submit" value="Generate pptx">
		<li><a href="{% url 'emplist:index' %}">Back to employee list</a></li>
	</form>

emplist/templates/emplist/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

emplist/templates/emplist/list.html
{% if user.is_authenticated %}
	{% if employee_list %}
		<ul>
		{% for emp in employee_list %}
			<li><a href="/emplist/{{ emp.id }}/detail">{{ emp }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No employees are available.</p>
	{% endif %}

	<li><a href="{% url 'emplist:registform' %}">regist</a></li>
{% else %}
	<li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
{% endif %}

emplist/templates/emplist/registform.html
	<form action="{% url 'emplist:regist' %}" method="post">
	{% csrf_token %}
		<p>First Name</p>
		<ul>
			<input type="text" name="firstname" >
		</ul>
		<p>Last Name</p>
		<ul>
			<input type="text" name="lastname" >
		</ul>
		<p>Address</p>
		<ul>
			<input type="text" name="address" >
		</ul>
		<p>Phone</p>
		<ul>
			<input type="text" name="phone" >
		</ul>

		<input type="submit" value="Register">
		<li><a href="{% url 'emplist:index' %}">Back to employee list</a></li>
	</form>